sudo: required
services:
  - docker

before_install:
  - docker build -t eddiedj/pinterest-test -f ./client/dev.Dockerfile ./client

script:
  - node ./testTest.js

after_success:
  - docker build -t eddiedj/pinterest-client ./client
  - docker build -t eddiedj/pinterest-nginx ./nginx
  - docker build -t eddiedj/pinterest-server ./server
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eddiedj/pinterest-client
  - docker push eddiedj/pinterest-nginx
  - docker push eddiedj/pinterest-server

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: pinterest-docker
  env: PinterestDocker-env
  bucket_name: elasticbeanstalk-us-west-2-670225287603
  bucket_path: pinterest-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
