version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: 'redis:latest'
  server:
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQLUSER=mysql
      - MYSQLHOST=mysql
      - MYSQLDATABASE=mysql
      - MYSQLPASSWORD=mysqlpassword
      - MYSQLPORT=3306
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
