version: '3'
services:
  mysql:
    build:
      dockerfile: dev.Dockerfile
      context: ./mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pinterest
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    # 'DUXt2pi_hMOIcQ2EeXklFTUY',
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MYSQLHOST=mysql
      - MYSQLUSER=testuser
      - MYSQLDATABASE=pinterest
      - MYSQLPASSWORD=testpassword
      - MYSQLPORT=3306
      - WAIT_HOSTS=mysql:3306
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
